name: Build and Deploy Next.js Server to Rumahweb

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode dari Repository
        uses: actions/checkout@v4

      - name: Setup Node.js di GitHub
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Kirim File Produksi ke Rumahweb via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Bagian ini penting: Kita kirim file proyek inti, folder hasil build, dan node_modules
          # secara default akan mengirimkan seluruh isi direktori kerja saat ini
          server-dir: ./
